### ISSUE TITLE
Home - individual cities should be links to their respective interior page (city)

### ISSUE THREAD

**Issue by kelaine** [BraveUX/uber-offices-new#3]
![screen shot 2015-05-20 at 1 20 04 pm](https://cloud.githubusercontent.com/assets/9937697/7732053/f17dd92a-fef2-11e4-862a-eb59f7d9a515.png)

**Comment by sarahkleins** [comment]
The elements are now links. I've linked up the DC city page but the other individual city pages will be created with Wordpress.
