### ISSUE TITLE
Universal - increase font size

### ISSUE THREAD

**Issue by kelaine** [BraveUX/uber-offices-new#4]
![screen shot 2015-05-20 at 1 21 03 pm](https://cloud.githubusercontent.com/assets/9937697/7732080/1ddf3dec-fef3-11e4-9222-0741c6b638e7.png)

**Comment by sarahkleins** [comment]
Text size on mockup is 12px / 1.5 line height, live site is 1.2rem (12px) / 1.5 line height.
