### ISSUE TITLE
Cities - nav - padding and placement of city in navigation

### ISSUE THREAD

**Issue by kelaine** [BraveUX/uber-offices-new#9]
![screen shot 2015-05-20 at 1 54 31 pm](https://cloud.githubusercontent.com/assets/9937697/7732736/f48b48f0-fef7-11e4-9aac-8f98c5838a5d.png)

**Comment by sarahkleins** [comment]
@theastralj said to have this in Montserrat.

**Comment by sarahkleins** [comment]
Fixed with aecf77371a91a5858c7438415ad586740562259d
